version: 0.2
## This is meant to run on amazonlinux:2017.03.1.20170812 docker image

phases:
  install:
    commands:
      - yum -y update
      - yum -y install zip
      - yum -y install python36
      - yum -y install python36-pip
  pre_build:
    commands:
      - curl -O https://bootstrap.pypa.io/get-pip.py
      - python3 get-pip.py
      - export SOURCE_DIR=pytorch_lambda_poc
  build:
    commands:
      # Build and run tests to make sure all ok
      - pip install -r tests/requirements_test.txt
      - pip install pytest
      - pytest

  post_build:
    commands:
    # Create the build package
      - echo creating package
      - mkdir buildoutput
    # The requirements build for lambda
      - pip install -r $SOURCE_DIR/requirements_lambda.txt  -t $SOURCE_DIR
    # Install torch without cuda on linux
      - pip install http://download.pytorch.org/whl/cpu/torch-0.4.0-cp36-cp36m-linux_x86_64.whl -t $SOURCE_DIR
      - cd $SOURCE_DIR && zip -r9 ../buildoutput/$SOURCE_DIR.zip . -x **/__pycache__/** **/tests/** && cd ..


artifacts:
  files:
    - '**/*'
  base-directory: buildoutput