version: 0.2
## This is meant to run on amazonlinux docker image amazonlinux:2018.03.0.20180424
phases:
  install:
    commands:
      - yum -y update
      - yum -y install zip
      - yum -y install python36
      - yum -y install python36-pip
      - yum -y install bzip2

  pre_build:
    commands:
      # Install conda
      - curl -O https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
      - bash Miniconda3-latest-Linux-x86_64.sh -b

      #Install pip
      - curl -O https://bootstrap.pypa.io/get-pip.py
      - python3 get-pip.py

  build:
    commands:
      # Build and run tests to make sure all ok
#      - pip install -r source/requirements_dev.txt
#      - pip install pytest
#      - pytest

  post_build:
    commands:
    # Set up conda env
      - echo creating package
      - ~/miniconda3/bin/conda create --yes --name buildenv python=3.6
      - source ~/miniconda3/bin/activate buildenv

    # The requirements build for lambda
      - ~/miniconda3/bin/conda install --yes --file source/requirements_lambda.txt -n buildenv

    # Install torch without cuda on linux
      - ~/miniconda3/bin/conda install --yes pytorch-cpu -c pytorch -n buildenv

    # Zip package
      - mkdir buildoutput
      - ls -l  ~/miniconda3/envs/buildenv/lib
      - cp -r  ~/miniconda3/envs/buildenv/lib/python3.6/site-packages/* source
      - cp ~/miniconda3/envs/buildenv/lib/*.* source || :
      - ls -l
      - cd source && zip -r ../buildoutput/pytorchzip_lambda_package.zip . -x test*/* && cd ..
      - zip -r ../buildoutput/condalib.zip ~/miniconda3/envs/buildenv/lib


artifacts:
  files:
    - '**/*'
  base-directory: buildoutput