version: 0.2
## This is meant to run on amazonlinux docker image amazonlinux:2017.03.1.20170812 to work on lambda
phases:
  install:
    commands:
      - yum -y update
      - yum -y install zip
      - yum -y install python36
      - yum -y install python36-pip
      - yum -y install bzip2
      - yum -y install  unzip
      - yum install -y zlib zlib-devel openssl openssl-devel
      - yum install -y cmake make automake gcc gcc-c++ kernel-devel
      - yum install -y git
      - yum install -y python36-devel

  pre_build:
    commands:


      #Install pip
      - curl -O https://bootstrap.pypa.io/get-pip.py
      - python3 get-pip.py



  build:
    commands:
      # Build and run tests to make sure all ok
#      - pip install -r source/requirements_dev.txt
#      - pip install pytest
#      - pytest

  post_build:
    commands:
      - pip install virtualenv
      - virtualenv ~/lambdavenv
      - source ~/lambdavenv/bin/activate
    # pip installs

      - pip install Pillow
      - pip install cython   # numpy dependency
      - pip install pyyaml   # pytorch dependency


# numpy install form source
      - git clone --recursive https://github.com/numpy/numpy.git
      - cd numpy
      - git checkout 31465473c491829d636c9104c390062cba005681  # latest release
      - pip install setuptools
      - python setup.py install
      - cd ..

# pytorch install from source
      - curl --output pytorch_source.zip https://codeload.github.com/pytorch/pytorch/zip/af3964a8725236c78ce969b827fdeee1c5c54110
      - ls -l
      - unzip pytorch_source.zip -d pytorch_source
    #  - git checkout af3964a8725236c78ce969b827fdeee1c5c54110
      - export NO_CUDA=1  # reduce package size (pointless b/c AWS Lambda does not have these capabilities anyways)
      - export NO_CUDNN=1

      - cd pytorch_source/pytorch-af3964a8725236c78ce969b827fdeee1c5c54110 && ls -l
      - git submodule update --init
      - python setup.py install
      - cd



    # Zip package
      - mkdir buildoutput
      - cd $VIRTUAL_ENV/lib/python3.6/site-packages
      - zip -r9 ~/buildoutput/pytorchzip_lambda_package.zip *
      - cd
      - cd source && zip -r ~/buildoutput/pytorchzip_lambda_package.zip . -x test*/* && cd ..



artifacts:
  files:
    - '**/*'
  base-directory: buildoutput